# Generated by Django 3.2.10 on 2022-03-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220330_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermpin',
            name='encrypted_ciphertext',
        ),
        migrations.RemoveField(
            model_name='usermpin',
            name='encrypted_remainder',
        ),
    ]
