# Generated by Django 3.2.10 on 2022-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220331_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermpin',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
