# Generated by Django 3.2.10 on 2022-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermpin_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermpin',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
