
variables:
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

default:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  services:
    - mysql:8.0
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
     - apt -y install apt-utils
     - apt -y install net-tools python3.8 python3-pip mysql-client libmysqlclient-dev
     - apt -y upgrade
     - pip3 install -r requirements.txt


 migrations:
   stage: build
   script:
     - cd ~


 django-tests:
   stage: test
   script:
     - echo "GRANT ALL on *.* to '${MYSQL_USER}';"| mysql -u root --password="${MYSQL_ROOT_PASSWORD}" -h mysql
deploy_to_aws:
  stage: deploy
  script:
  - aws deploy push --application-name myApp --s3-location s3://group5asdc/artifacts.zip
  - aws deploy create-deployment --application-name myApp --deployment-group-name asdc-group-5-DeploymentGroup --s3-location bucket=group5asdc,bundleType=zip,key=artifacts.zip
  artifacts:
    paths:
    - public