version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 3000
      runas: root