# Generated by Django 3.2.10 on 2022-03-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_notes_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
