# Generated by Django 3.2.10 on 2022-03-27 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
