# Generated by Django 3.2.10 on 2022-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220327_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='start_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'HIGH'), (1, 'NORMAL'), (2, 'LOW')], default=0),
            preserve_default=False,
        ),
    ]
