# Generated by Django 3.2.10 on 2022-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20220330_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='encrypted_remainder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
