# Generated by Django 3.2.10 on 2022-03-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_vault_encrypted_remainder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vault',
            old_name='website',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='vault',
            name='website_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
