# Generated by Django 3.2.10 on 2022-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_auto_20220331_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='website_username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
